name: ReactNative-SDK Tests

on:
  pull_request:
    branches:
      - main
      - release/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true
env:
  NODE_VERSION: '20'
  RC_SUFFIX: 'rc'
jobs:
  test-react-sdk:
    runs-on: macos-14
    steps:
      # Git clone repository
      - name: Git clone repository
        uses: actions/checkout@v4
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Install dependencies
      - name: Install dependencies
        run: yarn set version 3.6.1 && yarn
      # Run lint 
      - name: Run lint
        run: yarn lint
        continue-on-error: false
      # Run test 
      - name: Run Test
        run: yarn test
        continue-on-error: true